### PR TITLE
WIP Manifesto Driven Development

### PR DESCRIPTION
**Pull request by RichardLitt**

### CODE REVIEW

**Comment by RichardLitt** [comment]
Not yet! I'm hoping to start with something later today or this weekend, though.

**Comment by RichardLitt** [comment]
@noffle I've written up an example, in the README for [Katahdin](https://github.com/mntnr/katahdin). What do you think about it? Does it make sense what I meant now?

**Comment by noffle** [comment]
@RichardLitt 

1. Cool name :+1: 
2. I really like having a write-up that explains both a) the problem the module solves, and b) how it works. I wish more modules included these kinds of details. "Why does this exist!?"
3. A usage example would really drive the understanding home for me. I understand this is WIP though, so this might already be forthcoming.
4. I dig the project itself: a simple CLI app that I could run in my project dir and get a list of newline-delimited keywords to stdout would be *super cool*! Props if it has works offline, maybe /w degraded quality.

**Comment by RichardLitt** [comment]
1. Thanks. 2. Thanks. 3. Yes. WIP! 4. Word.

I think it is setting the intentions which is important. Somewhat similar to Readme-Driven Development, but more about setting the _why_ first.

**Comment by RichardLitt** [comment]
Closing as stale. Interesting stuff here, but priorities.

**Pull request closed without merging**
